### ISSUE TITLE
Citing EEGlib

### ISSUE THREAD

**Issue by phyk** [Xiul109/eeglib#1]
Hello,
I am interested in using this library for the calculation of the eeglib parameters in my master thesis project.
To use this project, I want to correctly reference it in my thesis. How would you prefer to have it cited?
Maybe you could include an example reference in the Readme file?

**Comment by Xiul109** [comment]
Hi,
Sorry for the delay. I'm not very active in GitHub lately. I'm glad my project is useful for you. You can cite this paper: [https://link.springer.com/article/10.1007/s12652-019-01592-9](https://link.springer.com/article/10.1007/s12652-019-01592-9).

I will clarify this better in the readme file for further users.
