### ISSUE TITLE
hallo, can you help me? when i run my csv file using CSVHelper, the code was error 

### ISSUE THREAD

**Issue by Ss2345** [Xiul109/eeglib#2]

**Comment by Ss2345** [comment]
hallo, can you help me? i'am having a trouble when i run CSVHelper to read my csv file. how can fix it? thank you

**Comment by Xiul109** [comment]
Hi! I can take a look if you send me your file. Maybe it needs some additional parameters or perhaps the file has an strange structure, but if I don't see it I can't help.
