### ISSUE TITLE
Clarify data structure required for input. 

### ISSUE THREAD

**Issue by matiasandina** [Xiul109/eeglib#4]
My original data is stored as `.raw` in a one dimensional vector that I have to reshape. I can do this using numpy without issue, but I guess there is no current way to feed a numpy array to the `Wrapper`.
What would be the best way to structure the pipeline to be able to use the `EEG` class without saving my data again to a `.csv` file?
My desired pipeline would look something like this:
band pass filter 0.5-128Hz -> downsample to 128 Hz -> calculate features using sliding window of different lengths.

Just to illustrate what I have tried

```
# eeg_mean is a numpy array of shape (N, )
# This fails because of allocation 
# MemoryError: Unable to allocate 70.9 TiB for an array with shape (324632576, 30000) and data type float64
helper = Helper(
  data = eeg_mean[:, None],
  windowSize= 1 * f_aq,
  sampleRate = f_aq, 
  lowpass = bandpass_freqs[0], highpass  = bandpass_freqs[1], 
  normalize = False, ICA = False)
```

This doesn't fail due to error but I don't think this is the most efficient way to do it
```
sliding_window_secs = 4
window = sliding_window_secs * f_aq
EEG = eeglib.eeg.EEG(windowSize=window, sampleRate=f_aq, channelNumber=1)
windows_to_calculate = eeg_mean.shape[0]//window
bands_dict = {"delta": (1, 4),
              "theta": (5, 11)}
bandPower_dict = {"delta": [], "theta": []}
import timeit
start_time = timeit.default_timer()
for i in range(windows_to_calculate):
  EEG.set(eeg_mean[window*i:window * (i+1), None])
  # put bandpower results in dictionary
  band_d = EEG.bandPower(bands=bands_dict)[0]
  bandPower_dict['delta'].extend([band_d['delta']])
  bandPower_dict['theta'].extend([band_d['theta']])
```

**Comment by Xiul109** [comment]
Hi.

I think you are commiting a mistake when initializing the Helper. By looking at the [documentation of the Helper](https://eeglib.readthedocs.io/en/latest/helpers.html#eeglib.helpers.Helper), you can see the next: "The signals data in the shape (nChannels, nSamples)". I think the data you are using follows the inverse format, so it is interpreted like having lots of channels with only one value in each of them. Let me know if that solves your problem and sorry for the late answer, I'm really busy lately.

**Comment by matiasandina** [comment]
Hello,
This seems to solve the issue, my bad!

**Comment by matiasandina** [comment]
Sorry for re-opening this....the helper command runs, but I'm facing issues with the data that is being used there.

```
>>> helper = Helper(
...     data = np.arange(0,10000,1).reshape(1,10000), #eeg_mean.reshape(1, len(eeg_mean)),
...     windowSize= 1,
...     sampleRate = f_aq, 
...     lowpass = bandpass_freqs[0], highpass  = bandpass_freqs[1], 
...     normalize = False, ICA = False)
>>> helper.data
array([[-9223372036854775808, -9223372036854775808, -9223372036854775808,
        ..., -2031548101102705664, -1687638451523488256,
        -1385620542168139264]])
>>> np.arange(0,10000,1).reshape(1,10000)
array([[   0,    1,    2, ..., 9997, 9998, 9999]])
```

When reshaping with `eeg_mean.reshape(1, len(eeg_mean))`
I was getting all `nan`, not clear what's going on here.

**Comment by Xiul109** [comment]
Sorry for not answering before. I tried to reproduce your error, but i can't  because I don't know the parameters you are using, neither your data. If you could provide me more info, I'd probably be able to solve your problem.

Again, sorry for the delayed answer.
