### ISSUE TITLE
sklearn vs scikit-learn dependancy

### ISSUE THREAD

**Issue by FloMrt** [Xiul109/eeglib#5]
Hi !

Thank you for your great work.
Just one request... could you update your requirements.txt / setup.py to include scikit-learn instead of sklearn (it is the recommanded way because sklearn just install scikit-learn) ?
Because the version of sklearn is always 0.0 and its license is "UNKNOWN" (in its metadata) and it messes with some checker :(

Thanks for your help !

**Comment by Xiul109** [comment]
Thanks for taking this into my knowledge. Now it's been fixed.
