### ISSUE TITLE
Need to get the features from an eeg between an starting an ending point

### ISSUE THREAD

**Issue by webcluster4u** [Xiul109/eeglib#7]
Hi,

according to the documentation, a typical example to get eeg features is likie below:

```
helper= EDFHelper("sampleedf",windowSize=1000)
for eeg in helper:
    print(eeg.PFD())
```

But, I need to get just one eeg which have all points from one timestamp to another timestamp and then get all features. How to do this with eeglib?

**Comment by Xiul109** [comment]
If I understand correctly, you want to extract all your features using only one window. This can be done using the same sample code you show in your comment, but changing the windowSize to the size of the number of samples of your data.
